name: Enforce PR Labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.2.2
      with:
        REQUIRED_LABELS_ANY: "feature,fix,chore,dependencies"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Please apply one label ['feature','fix','chore']"
